/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCompleteProfileRouteImport } from './routes/_authenticated/complete-profile'
import { Route as AuthenticatedDonorRouteImport } from './routes/_authenticated/donor'
import { Route as AuthenticatedDonorsIndexRouteImport } from './routes/_authenticated/donors.index'
import { Route as AuthenticatedDonorsDonorIdRouteImport } from './routes/_authenticated/donors.$donorId'
import { Route as AuthenticatedDonorsNewRouteImport } from './routes/_authenticated/donors.new'
import { Route as AuthenticatedDonorsEditDonorIdRouteImport } from './routes/_authenticated/donors.edit.$donorId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompleteProfileRoute =
  AuthenticatedCompleteProfileRouteImport.update({
    id: '/complete-profile',
    path: '/complete-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDonorRoute = AuthenticatedDonorRouteImport.update({
  id: '/donor',
  path: '/donor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDonorsIndexRoute =
  AuthenticatedDonorsIndexRouteImport.update({
    id: '/donors/',
    path: '/donors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDonorsDonorIdRoute =
  AuthenticatedDonorsDonorIdRouteImport.update({
    id: '/donors/$donorId',
    path: '/donors/$donorId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDonorsNewRoute = AuthenticatedDonorsNewRouteImport.update({
  id: '/donors/new',
  path: '/donors/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDonorsEditDonorIdRoute =
  AuthenticatedDonorsEditDonorIdRouteImport.update({
    id: '/donors/edit/$donorId',
    path: '/donors/edit/$donorId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/donor': typeof AuthenticatedDonorRoute
  '/donors/$donorId': typeof AuthenticatedDonorsDonorIdRoute
  '/donors/new': typeof AuthenticatedDonorsNewRoute
  '/donors/': typeof AuthenticatedDonorsIndexRoute
  '/donors/edit/$donorId': typeof AuthenticatedDonorsEditDonorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/donor': typeof AuthenticatedDonorRoute
  '/donors/$donorId': typeof AuthenticatedDonorsDonorIdRoute
  '/donors/new': typeof AuthenticatedDonorsNewRoute
  '/donors': typeof AuthenticatedDonorsIndexRoute
  '/donors/edit/$donorId': typeof AuthenticatedDonorsEditDonorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/_authenticated/donor': typeof AuthenticatedDonorRoute
  '/_authenticated/donors/$donorId': typeof AuthenticatedDonorsDonorIdRoute
  '/_authenticated/donors/new': typeof AuthenticatedDonorsNewRoute
  '/_authenticated/donors/': typeof AuthenticatedDonorsIndexRoute
  '/_authenticated/donors/edit/$donorId': typeof AuthenticatedDonorsEditDonorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/complete-profile'
    | '/donor'
    | '/donors/$donorId'
    | '/donors/new'
    | '/donors/'
    | '/donors/edit/$donorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/complete-profile'
    | '/donor'
    | '/donors/$donorId'
    | '/donors/new'
    | '/donors'
    | '/donors/edit/$donorId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/complete-profile'
    | '/_authenticated/donor'
    | '/_authenticated/donors/$donorId'
    | '/_authenticated/donors/new'
    | '/_authenticated/donors/'
    | '/_authenticated/donors/edit/$donorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complete-profile': {
      id: '/_authenticated/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof AuthenticatedCompleteProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/donor': {
      id: '/_authenticated/donor'
      path: '/donor'
      fullPath: '/donor'
      preLoaderRoute: typeof AuthenticatedDonorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/donors/': {
      id: '/_authenticated/donors/'
      path: '/donors'
      fullPath: '/donors/'
      preLoaderRoute: typeof AuthenticatedDonorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/donors/$donorId': {
      id: '/_authenticated/donors/$donorId'
      path: '/donors/$donorId'
      fullPath: '/donors/$donorId'
      preLoaderRoute: typeof AuthenticatedDonorsDonorIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/donors/new': {
      id: '/_authenticated/donors/new'
      path: '/donors/new'
      fullPath: '/donors/new'
      preLoaderRoute: typeof AuthenticatedDonorsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/donors/edit/$donorId': {
      id: '/_authenticated/donors/edit/$donorId'
      path: '/donors/edit/$donorId'
      fullPath: '/donors/edit/$donorId'
      preLoaderRoute: typeof AuthenticatedDonorsEditDonorIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCompleteProfileRoute: typeof AuthenticatedCompleteProfileRoute
  AuthenticatedDonorRoute: typeof AuthenticatedDonorRoute
  AuthenticatedDonorsDonorIdRoute: typeof AuthenticatedDonorsDonorIdRoute
  AuthenticatedDonorsNewRoute: typeof AuthenticatedDonorsNewRoute
  AuthenticatedDonorsIndexRoute: typeof AuthenticatedDonorsIndexRoute
  AuthenticatedDonorsEditDonorIdRoute: typeof AuthenticatedDonorsEditDonorIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCompleteProfileRoute: AuthenticatedCompleteProfileRoute,
  AuthenticatedDonorRoute: AuthenticatedDonorRoute,
  AuthenticatedDonorsDonorIdRoute: AuthenticatedDonorsDonorIdRoute,
  AuthenticatedDonorsNewRoute: AuthenticatedDonorsNewRoute,
  AuthenticatedDonorsIndexRoute: AuthenticatedDonorsIndexRoute,
  AuthenticatedDonorsEditDonorIdRoute: AuthenticatedDonorsEditDonorIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
